application: nuntio-cms
version: 1
runtime: python
api_version: 1

default_expiration: '3650d'

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  secure: optional
  login: admin

- url: /media
  static_dir: _generated_media
  secure: optional

- url: /admin/.*
  script: common/appenginepatch/main.py
  login: admin

- url: /canvas.html
  static_files: templates/static/canvas.html
  upload: templates/static/canvas.html

- url: /rpc_relay.html
  static_files: templates/static/rpc_relay.html
  upload: templates/static/rpc_relay.html

- url: /robots.txt
  static_files: templates/static/robots.txt
  upload: templates/static/robots.txt

- url: /.*
  script: common/appenginepatch/main.py
  secure: optional
  login: admin
